services:
  api:
    build:
      context: ./api_server
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/laundry

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laundry
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d # initialize db schema + tables
      - postgres_data:/var/lib/postgresql/data

  dashboard:
    build:
      context: ./dashboard
      dockerfile: dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laundry

volumes:
  postgres_data: