CREATE SCHEMA IF NOT EXISTS laundry;

CREATE TABLE IF NOT EXISTS laundry.accelerometer_signal_logs (
    id SERIAL PRIMARY KEY,
    device_id TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION,
    z DOUBLE PRECISION
);